#!/usr/bin/env python3
"""
Inspect target equations from multi-rule datasets.

This script helps developers understand what equations are generated by
multi-rule datasets for debugging and verification purposes.

Usage:
    python scripts/inspect_multi_rule_targets.py --num_rules 4 --num_problems 10
    python scripts/inspect_multi_rule_targets.py --num_rules 2 --num_problems 20
"""
import argparse
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.algebra.algebra_dataset import MultiRuleDataset


def main():
    parser = argparse.ArgumentParser(
        description="Inspect target equations from multi-rule datasets"
    )
    parser.add_argument(
        '--num_rules',
        type=int,
        default=4,
        choices=[2, 3, 4],
        help='Number of rules to chain (default: 4)'
    )
    parser.add_argument(
        '--num_problems',
        type=int,
        default=10,
        help='Number of problems to generate and display (default: 10)'
    )
    parser.add_argument(
        '--seed',
        type=int,
        default=42,
        help='Random seed for reproducibility (default: 42)'
    )
    
    args = parser.parse_args()
    
    print(f"\nGenerating Multi-Rule-{args.num_rules} Dataset...")
    dataset = MultiRuleDataset(
        num_rules=args.num_rules,
        num_problems=args.num_problems,
        seed=args.seed
    )
    
    print(f"\nMulti-Rule-{args.num_rules} Target Equations:")
    print("=" * 80)
    
    for i in range(min(args.num_problems, len(dataset))):
        info = dataset.get_problem_info(i)
        print(f"\n{i+1}. Target: {info['target_equation']}")
        print(f"   Input:  {info['input_equation']}")
        print(f"   Rules:  {' → '.join(info['rules_applied'])}")
        if 'solution' in info:
            print(f"   Solution: x = {info['solution']}")
    
    print("\n" + "=" * 80)
    print(f"\nTotal problems generated: {len(dataset)}")
    print(f"Dataset info: {dataset.get_dataset_info()}\n")


if __name__ == "__main__":
    main()
